name: firebase_chat
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.10.0
  cloud_firestore: ^4.6.0
  firebase_database: ^10.1.2
  firebase_auth: ^4.4.2
  google_sign_in: ^6.1.0
  flutter_facebook_auth: ^5.0.8
  provider: ^6.0.5
  flutter_svg: ^2.0.5
  logger: ^1.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  copy_with_extension_gen: ^5.0.2
  dartz: ^0.10.1
  http: ^0.13.5
  shared_preferences: ^2.1.0
  advanced_shadows: ^0.0.1
  flex_color_scheme: ^7.0.4
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  google_maps_flutter: ^2.2.6
  json_annotation: ^4.8.1
  firebase_storage: ^11.1.2
  loading_animation_widget: ^1.2.0+4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.2

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/icons/
    - assets/sticker/